const movieTitles = [
  "The Shawshank Redemption",
  "The Godfather",
  "The Dark Knight",
  "The Godfather Part II",
  "12 Angry Men",
  "Schindler's List",
  "The Lord of the Rings: The Return of the King",
  "Pulp Fiction",
  "The Good, the Bad and the Ugly",
  "Fight Club",
  "Forrest Gump",
  "Inception",
  "The Lord of the Rings: The Fellowship of the Ring",
  "Star Wars: Episode V - The Empire Strikes Back",
  "The Lord of the Rings: The Two Towers",
  "The Matrix",
  "Goodfellas",
  "One Flew Over the Cuckoo's Nest",
  "Se7en",
  "Seven Samurai",
  "It's a Wonderful Life",
  "The Silence of the Lambs",
  "City of God",
  "Saving Private Ryan",
  "Spirited Away",
  "The Green Mile",
  "Interstellar",
  "Léon: The Professional",
  "The Usual Suspects",
  "Harakiri",
  "The Lion King",
  "Back to the Future",
  "The Pianist",
  "Terminator 2: Judgment Day",
  "American History X",
  "Psycho",
  "Gladiator",
  "City Lights",
  "The Departed",
  "The Intouchables",
  "Whiplash",
  "The Prestige",
  "The Lion King",
  "Memento",
  "Apocalypse Now",
  "Alien",
  "Sunset Blvd.",
  "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
  "The Great Dictator",
  "Cinema Paradiso",
  "The Shining",
  "Grave of the Fireflies",
  "Avengers: Endgame",
  "Joker",
  "Toy Story",
  "Inglourious Basterds",
  "The Dark Knight Rises",
  "Spider-Man: Into the Spider-Verse",
  "My Neighbor Totoro",
  "Princess Mononoke",
  "Howl's Moving Castle",
  "Castle in the Sky",
  "Kiki's Delivery Service",
  "Nausicaä of the Valley of the Wind",
  "Ponyo",
  "The Wind Rises",
  "The Castle of Cagliostro",
  "The Secret World of Arrietty",
  "Farewell My Concubine",
  "A Beautiful Mind",
  "Crouching Tiger, Hidden Dragon",
  "Amélie",
  "The Lives of Others",
  "The Legend of 1900",
  "The Pursuit of Happyness",
  "Infernal Affairs",
  "Incendies",
  "3 Idiots",
  "The Truman Show",
  "Dangal",
  "Andhadhun",
  "Ratatouille",
  "The Sixth Sense",
  "Slumdog Millionaire",
  "Life Is Beautiful",
  "The Curious Case of Benjamin Button",
  "La La Land",
  "WALL·E",
  "Zootopia",
  "The Secret in Their Eyes",
  "The Pianist",
  "The Untouchables",
  "Big Fish",
  "Her",
  "Léon: The Professional",
  "The Girl with the Dragon Tattoo",
  "Children of Heaven",
  "The King's Speech",
  "The Imitation Game",
  "Atonement",
  "Pride and Prejudice",
  "Lock, Stock and Two Smoking Barrels",
  "Snatch",
  "The Theory of Everything",
  "Billy Elliot",
  "Trainspotting",
  "Love Actually",
  "The Elephant Man",
  "The Full Monty",
  "Shakespeare in Love",
  "Notting Hill",
  "The Best Exotic Marigold Hotel",
  "Titanic",
];

module.exports = { movieTitles };
